[package]
name = "app"
edition = { workspace = true }
version = { workspace = true }
authors = { workspace = true }
description = "fedimint tauri app"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
base64 = "0.22.1"
fedimint-api-client = { workspace = true }
fedimint-bip39 = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tauri = { version = "2.5.1", features = [] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }
