[package]
name = "fedimint-logging"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "contains some utilities for logging and tracing"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[features]
telemetry = [
    "tracing-opentelemetry",
    "opentelemetry-jaeger",
    "console-subscriber",
    "opentelemetry"
]

[lib]
name = "fedimint_logging"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
console-subscriber = { workspace = true, optional = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry-jaeger = { workspace = true, optional = true }
tracing-opentelemetry = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
