[package]
name = "fedimint-server-bitcoin-rpc"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Bitcoin RPC implementations for Fedimint server"
license = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }

[lib]
name = "fedimint_server_bitcoin_rpc"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitcoin = { workspace = true }
bitcoincore-rpc = { workspace = true }
esplora-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
tracing = { workspace = true } 
